### ISSUE TITLE
bug tool not found with shift_longitudes on climate.usegalaxy.eu

### ISSUE THREAD

**Issue by annefou** [NordicESMhub/galaxy-tools#29]
python3: can't open file '/opt/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/climate/shift_longitudes/5708a3a46f2e/shift_longitudes/shift_lon.py': [Errno 2] No such file or directory

I am not sure what is wrong but I used  $__tool_directory__/shift_lon.py but it appears to be different on climate.usegalaxy.eu 
@bgruening Any idea?

**Comment by annefou** [comment]
Same problem with cds_essential_variability. Maybe $tool_directory is not correct?

python3: can't open file '/opt/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/climate/cds_essential_variability/8b30be2cef81/cds_essential_variability/ecv_retrieve.py': [Errno 2] No such file or directory

**Comment by bgruening** [comment]
try again in 5min, I forgot to sync ...

**Comment by bgruening** [comment]
both tools ...

**Comment by annefou** [comment]
It seems to work now so we close this issue.
