### ISSUE TITLE
Add FATES model

### ISSUE THREAD

**Issue by annefou** [NordicESMhub/galaxy-tools#39]
Functionally Assembled Terrestrial Ecosystem Simulator (FATES) with CLM (Community Land Model).

**requested by**: ecologists (Bergen and Tromso), Climate scientists (Oslo).
 **Github repo**: 
- https://github.com/NGEET/fates
- https://github.com/ESCOMP/CTSM 

**info**: special configuration of CTSM (uses CESM framework).

The plan is to add it in Galaxy so ecologist can run single point simulations from a list of locations corresponding to in-situ stations.

+ add tools for visualization (hopefull we can re-use some existing tool).

See http://web.nateko.lu.se/lpj-guess/education/ getting an idea of what we can do (it uses a different model).

### Step - 1

- Fates is a component of CLM (very similar setup to CESM) which means it should be fairly easy to add in in bioconda
- Prepare a list of sites and corresponding input data
- Create xml wrapper for Galaxy

### Step - 2

- Create visualization tools

**Comment by annefou** [comment]
@huitang-earth For your information, this is where we will build the tool wrapper (graphical interface) for FATES).

We will create a branch (fates) for this. 

But first we need to package FATES for running out-of-the-box.

**Comment by huitang-earth** [comment]
@annefou This looks like a good start. Please let me know if the virtual machine has been built for running FATES.

**Comment by annefou** [comment]
For visualization one option mentioned is what is done for PECAN project https://pecanproject.github.io/index.html

**Comment by annefou** [comment]
@huitang-earth Start draft for FATES tutorial (branch fates https://github.com/NordicESMhub/galaxy-training-material). Tutorial for fates is in 
https://github.com/NordicESMhub/galaxy-training-material/tree/fates/topics/climate/tutorials/fates

**Comment by annefou** [comment]
done. We will create further issues to improve the current tool. In particular for better handling different "compset" and input data.
